#include <bits/stdc++.h>
using namespace std;

/*
-------------------------------------------------------
Problem: 371. Sum of Two Integers
Difficulty: Medium
Topic: Bit Manipulation

Brute Force Approach:
- Use the '+' operator to add the two integers.

Time Complexity: O(1)
Space Complexity: O(1)

Optimal Approach (Bit Manipulation):
- XOR (^) adds the bits without considering the carry.
- AND (&) identifies the positions where a carry is generated.
- Left shift (<<) the carry by one position.
- Repeat the process until there is no carry left.

Time Complexity: O(1)
Space Complexity: O(1)

LeetCode:
https://leetcode.com/problems/sum-of-two-integers/
-------------------------------------------------------
*/

class Solution {
public:
    int getSum(int a, int b) {

        while (b != 0) {

            // Calculate the carry generated by common set bits
            int carry = (a & b) << 1;

            // Add without considering the carry
            a = a ^ b;

            // Carry will be added in the next iteration
            b = carry;
        }

        return a;
    }
};